// згенеровано tools/picker/build_catalog.py — сети для обиралки sets-picker.html
const CATALOG=[
{
"id": 511,
"cls": "warrior",
"group": "tier",
"label": "T0.5",
"name": "Battlegear of Heroism",
"faction": null,
"note": null,
"img": "_refs/picker/img/511.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=511"
},
{
"id": 209,
"cls": "warrior",
"group": "tier",
"label": "T1",
"name": "Battlegear of Might",
"faction": null,
"note": null,
"img": "_refs/picker/img/209.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=209"
},
{
"id": 218,
"cls": "warrior",
"group": "tier",
"label": "T2",
"name": "Battlegear of Wrath",
"faction": null,
"note": null,
"img": "_refs/picker/img/218.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=218"
},
{
"id": 523,
"cls": "warrior",
"group": "tier",
"label": "T3",
"name": "Dreadnaught's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/523.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=523"
},
{
"id": 655,
"cls": "warrior",
"group": "tier",
"label": "T4",
"name": "Warbringer Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/655.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=655"
},
{
"id": 654,
"cls": "warrior",
"group": "tier",
"label": "T4",
"name": "Warbringer Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/654.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=654"
},
{
"id": 657,
"cls": "warrior",
"group": "tier",
"label": "T5",
"name": "Destroyer Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/657.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=657"
},
{
"id": 656,
"cls": "warrior",
"group": "tier",
"label": "T5",
"name": "Destroyer Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/656.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=656"
},
{
"id": 672,
"cls": "warrior",
"group": "tier",
"label": "T6",
"name": "Onslaught Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/672.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=672"
},
{
"id": 673,
"cls": "warrior",
"group": "tier",
"label": "T6",
"name": "Onslaught Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/673.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=673"
},
{
"id": 788,
"cls": "warrior",
"group": "tier",
"label": "T7",
"name": "Dreadnaught Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/788.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=788"
},
{
"id": -19,
"cls": "warrior",
"group": "tier",
"label": "T7",
"name": "Valorous Dreadnaught Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-19.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-19"
},
{
"id": 830,
"cls": "warrior",
"group": "tier",
"label": "T8",
"name": "Siegebreaker Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/830.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=830"
},
{
"id": -79,
"cls": "warrior",
"group": "tier",
"label": "T8",
"name": "Conqueror's Siegebreaker Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-79.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-79"
},
{
"id": 867,
"cls": "warrior",
"group": "tier",
"label": "T9",
"name": "Wrynn's Battlegear",
"faction": "A",
"note": null,
"img": "_refs/picker/img/867.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=867"
},
{
"id": 868,
"cls": "warrior",
"group": "tier",
"label": "T9",
"name": "Hellscream's Battlegear",
"faction": "H",
"note": null,
"img": "_refs/picker/img/868.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=868"
},
{
"id": 895,
"cls": "warrior",
"group": "tier",
"label": "T10",
"name": "Ymirjar Lord's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/895.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=895"
},
{
"id": -240,
"cls": "warrior",
"group": "tier",
"label": "T10",
"name": "Sanctified Ymirjar Lord's Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-240.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-240"
},
{
"id": 567,
"cls": "warrior",
"group": "arena",
"label": "A1",
"name": "Gladiator's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/567.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=567"
},
{
"id": 701,
"cls": "warrior",
"group": "arena",
"label": "A2",
"name": "Merciless Gladiator's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/701.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=701"
},
{
"id": 736,
"cls": "warrior",
"group": "arena",
"label": "A3",
"name": "Vengeful Gladiator's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/736.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=736"
},
{
"id": -2,
"cls": "warrior",
"group": "arena",
"label": "A4",
"name": "Brutal Gladiator's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/-2.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-2"
},
{
"id": -53,
"cls": "warrior",
"group": "arena",
"label": "A5",
"name": "Deadly Gladiator's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/-53.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-53"
},
{
"id": -88,
"cls": "warrior",
"group": "arena",
"label": "A6",
"name": "Furious Gladiator's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/-88.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-88"
},
{
"id": -212,
"cls": "warrior",
"group": "arena",
"label": "A7",
"name": "Relentless Gladiator's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/-212.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-212"
},
{
"id": -266,
"cls": "warrior",
"group": "arena",
"label": "A8",
"name": "Wrathful Gladiator's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/-266.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-266"
},
{
"id": 189,
"cls": "warrior",
"group": "extra",
"label": "T0",
"name": "Battlegear of Valor",
"faction": null,
"note": null,
"img": "_refs/picker/img/189.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=189"
},
{
"id": 496,
"cls": "warrior",
"group": "extra",
"label": "T2.5",
"name": "Conqueror's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/496.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=496"
},
{
"id": 474,
"cls": "warrior",
"group": "extra",
"label": "ZG",
"name": "Vindicator's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/474.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=474"
},
{
"id": 384,
"cls": "warrior",
"group": "extra",
"label": "PvP",
"name": "Field Marshal's Battlegear",
"faction": "A",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/384.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=384"
},
{
"id": 383,
"cls": "warrior",
"group": "extra",
"label": "PvP",
"name": "Warlord's Battlegear",
"faction": "H",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/383.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=383"
},
{
"id": 516,
"cls": "paladin",
"group": "tier",
"label": "T0.5",
"name": "Soulforge Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/516.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=516"
},
{
"id": 208,
"cls": "paladin",
"group": "tier",
"label": "T1",
"name": "Lawbringer Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/208.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=208"
},
{
"id": 217,
"cls": "paladin",
"group": "tier",
"label": "T2",
"name": "Judgement Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/217.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=217"
},
{
"id": 528,
"cls": "paladin",
"group": "tier",
"label": "T3",
"name": "Redemption Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/528.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=528"
},
{
"id": 626,
"cls": "paladin",
"group": "tier",
"label": "T4",
"name": "Justicar Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/626.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=626"
},
{
"id": 625,
"cls": "paladin",
"group": "tier",
"label": "T4",
"name": "Justicar Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/625.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=625"
},
{
"id": 624,
"cls": "paladin",
"group": "tier",
"label": "T4",
"name": "Justicar Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/624.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=624"
},
{
"id": 629,
"cls": "paladin",
"group": "tier",
"label": "T5",
"name": "Crystalforge Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/629.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=629"
},
{
"id": 628,
"cls": "paladin",
"group": "tier",
"label": "T5",
"name": "Crystalforge Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/628.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=628"
},
{
"id": 627,
"cls": "paladin",
"group": "tier",
"label": "T5",
"name": "Crystalforge Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/627.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=627"
},
{
"id": 680,
"cls": "paladin",
"group": "tier",
"label": "T6",
"name": "Lightbringer Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/680.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=680"
},
{
"id": 679,
"cls": "paladin",
"group": "tier",
"label": "T6",
"name": "Lightbringer Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/679.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=679"
},
{
"id": 681,
"cls": "paladin",
"group": "tier",
"label": "T6",
"name": "Lightbringer Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/681.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=681"
},
{
"id": 789,
"cls": "paladin",
"group": "tier",
"label": "T7",
"name": "Redemption Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/789.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=789"
},
{
"id": -20,
"cls": "paladin",
"group": "tier",
"label": "T7",
"name": "Valorous Redemption Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-20.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-20"
},
{
"id": 820,
"cls": "paladin",
"group": "tier",
"label": "T8",
"name": "Aegis Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/820.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=820"
},
{
"id": -69,
"cls": "paladin",
"group": "tier",
"label": "T8",
"name": "Conqueror's Aegis Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-69.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-69"
},
{
"id": 877,
"cls": "paladin",
"group": "tier",
"label": "T9",
"name": "Turalyon's Battlegear",
"faction": "A",
"note": null,
"img": "_refs/picker/img/877.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=877"
},
{
"id": 878,
"cls": "paladin",
"group": "tier",
"label": "T9",
"name": "Liadrin's Battlegear",
"faction": "H",
"note": null,
"img": "_refs/picker/img/878.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=878"
},
{
"id": 900,
"cls": "paladin",
"group": "tier",
"label": "T10",
"name": "Lightsworn Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/900.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=900"
},
{
"id": -245,
"cls": "paladin",
"group": "tier",
"label": "T10",
"name": "Sanctified Lightsworn Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-245.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-245"
},
{
"id": 583,
"cls": "paladin",
"group": "arena",
"label": "A1",
"name": "Gladiator's Vindication",
"faction": null,
"note": null,
"img": "_refs/picker/img/583.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=583"
},
{
"id": 714,
"cls": "paladin",
"group": "arena",
"label": "A2",
"name": "Merciless Gladiator's Vindication",
"faction": null,
"note": null,
"img": "_refs/picker/img/714.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=714"
},
{
"id": 726,
"cls": "paladin",
"group": "arena",
"label": "A3",
"name": "Vengeful Gladiator's Vindication",
"faction": null,
"note": null,
"img": "_refs/picker/img/726.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=726"
},
{
"id": -15,
"cls": "paladin",
"group": "arena",
"label": "A4",
"name": "Brutal Gladiator's Vindication",
"faction": null,
"note": null,
"img": "_refs/picker/img/-15.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-15"
},
{
"id": -66,
"cls": "paladin",
"group": "arena",
"label": "A5",
"name": "Deadly Gladiator's Vindication",
"faction": null,
"note": null,
"img": "_refs/picker/img/-66.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-66"
},
{
"id": -101,
"cls": "paladin",
"group": "arena",
"label": "A6",
"name": "Furious Gladiator's Vindication",
"faction": null,
"note": null,
"img": "_refs/picker/img/-101.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-101"
},
{
"id": -213,
"cls": "paladin",
"group": "arena",
"label": "A7",
"name": "Relentless Gladiator's Vindication",
"faction": null,
"note": null,
"img": "_refs/picker/img/-213.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-213"
},
{
"id": -267,
"cls": "paladin",
"group": "arena",
"label": "A8",
"name": "Wrathful Gladiator's Vindication",
"faction": null,
"note": null,
"img": "_refs/picker/img/-267.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-267"
},
{
"id": 188,
"cls": "paladin",
"group": "extra",
"label": "T0",
"name": "Lightforge Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/188.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=188"
},
{
"id": 505,
"cls": "paladin",
"group": "extra",
"label": "T2.5",
"name": "Avenger's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/505.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=505"
},
{
"id": 475,
"cls": "paladin",
"group": "extra",
"label": "ZG",
"name": "Freethinker's Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/475.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=475"
},
{
"id": 402,
"cls": "paladin",
"group": "extra",
"label": "PvP",
"name": "Field Marshal's Aegis",
"faction": "A",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/402.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=402"
},
{
"id": 515,
"cls": "hunter",
"group": "tier",
"label": "T0.5",
"name": "Beastmaster Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/515.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=515"
},
{
"id": 206,
"cls": "hunter",
"group": "tier",
"label": "T1",
"name": "Giantstalker Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/206.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=206"
},
{
"id": 215,
"cls": "hunter",
"group": "tier",
"label": "T2",
"name": "Dragonstalker Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/215.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=215"
},
{
"id": 530,
"cls": "hunter",
"group": "tier",
"label": "T3",
"name": "Cryptstalker Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/530.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=530"
},
{
"id": 651,
"cls": "hunter",
"group": "tier",
"label": "T4",
"name": "Demon Stalker Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/651.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=651"
},
{
"id": 652,
"cls": "hunter",
"group": "tier",
"label": "T5",
"name": "Rift Stalker Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/652.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=652"
},
{
"id": 669,
"cls": "hunter",
"group": "tier",
"label": "T6",
"name": "Gronnstalker's Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/669.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=669"
},
{
"id": 794,
"cls": "hunter",
"group": "tier",
"label": "T7",
"name": "Cryptstalker Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/794.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=794"
},
{
"id": -25,
"cls": "hunter",
"group": "tier",
"label": "T7",
"name": "Valorous Cryptstalker Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-25.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-25"
},
{
"id": 838,
"cls": "hunter",
"group": "tier",
"label": "T8",
"name": "Scourgestalker Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/838.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=838"
},
{
"id": -87,
"cls": "hunter",
"group": "tier",
"label": "T8",
"name": "Conqueror's Scourgestalker Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-87.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-87"
},
{
"id": 859,
"cls": "hunter",
"group": "tier",
"label": "T9",
"name": "Windrunner's Battlegear",
"faction": "A",
"note": null,
"img": "_refs/picker/img/859.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=859"
},
{
"id": 860,
"cls": "hunter",
"group": "tier",
"label": "T9",
"name": "Windrunner's Pursuit",
"faction": "H",
"note": null,
"img": "_refs/picker/img/860.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=860"
},
{
"id": 891,
"cls": "hunter",
"group": "tier",
"label": "T10",
"name": "Ahn'Kahar Blood Hunter's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/891.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=891"
},
{
"id": -236,
"cls": "hunter",
"group": "tier",
"label": "T10",
"name": "Sanctified Ahn'Kahar Blood Hunter's Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-236.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-236"
},
{
"id": 586,
"cls": "hunter",
"group": "arena",
"label": "A1",
"name": "Gladiator's Pursuit",
"faction": null,
"note": null,
"img": "_refs/picker/img/586.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=586"
},
{
"id": 706,
"cls": "hunter",
"group": "arena",
"label": "A2",
"name": "Merciless Gladiator's Pursuit",
"faction": null,
"note": null,
"img": "_refs/picker/img/706.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=706"
},
{
"id": 723,
"cls": "hunter",
"group": "arena",
"label": "A3",
"name": "Vengeful Gladiator's Pursuit",
"faction": null,
"note": null,
"img": "_refs/picker/img/723.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=723"
},
{
"id": -7,
"cls": "hunter",
"group": "arena",
"label": "A4",
"name": "Brutal Gladiator's Pursuit",
"faction": null,
"note": null,
"img": "_refs/picker/img/-7.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-7"
},
{
"id": -58,
"cls": "hunter",
"group": "arena",
"label": "A5",
"name": "Deadly Gladiator's Pursuit",
"faction": null,
"note": null,
"img": "_refs/picker/img/-58.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-58"
},
{
"id": -93,
"cls": "hunter",
"group": "arena",
"label": "A6",
"name": "Furious Gladiator's Pursuit",
"faction": null,
"note": null,
"img": "_refs/picker/img/-93.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-93"
},
{
"id": -219,
"cls": "hunter",
"group": "arena",
"label": "A7",
"name": "Relentless Gladiator's Pursuit",
"faction": null,
"note": null,
"img": null,
"url": "https://www.wowhead.com/wotlk/item-set=-219"
},
{
"id": -273,
"cls": "hunter",
"group": "arena",
"label": "A8",
"name": "Wrathful Gladiator's Pursuit",
"faction": null,
"note": null,
"img": "_refs/picker/img/-273.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-273"
},
{
"id": 186,
"cls": "hunter",
"group": "extra",
"label": "T0",
"name": "Beaststalker Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/186.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=186"
},
{
"id": 509,
"cls": "hunter",
"group": "extra",
"label": "T2.5",
"name": "Striker's Garb",
"faction": null,
"note": null,
"img": "_refs/picker/img/509.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=509"
},
{
"id": 477,
"cls": "hunter",
"group": "extra",
"label": "ZG",
"name": "Predator's Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/477.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=477"
},
{
"id": 395,
"cls": "hunter",
"group": "extra",
"label": "PvP",
"name": "Field Marshal's Pursuit",
"faction": "A",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/395.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=395"
},
{
"id": 396,
"cls": "hunter",
"group": "extra",
"label": "PvP",
"name": "Warlord's Pursuit",
"faction": "H",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/396.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=396"
},
{
"id": 512,
"cls": "rogue",
"group": "tier",
"label": "T0.5",
"name": "Darkmantle Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/512.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=512"
},
{
"id": 204,
"cls": "rogue",
"group": "tier",
"label": "T1",
"name": "Nightslayer Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/204.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=204"
},
{
"id": 213,
"cls": "rogue",
"group": "tier",
"label": "T2",
"name": "Bloodfang Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/213.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=213"
},
{
"id": 524,
"cls": "rogue",
"group": "tier",
"label": "T3",
"name": "Bonescythe Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/524.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=524"
},
{
"id": 621,
"cls": "rogue",
"group": "tier",
"label": "T4",
"name": "Netherblade",
"faction": null,
"note": null,
"img": "_refs/picker/img/621.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=621"
},
{
"id": 622,
"cls": "rogue",
"group": "tier",
"label": "T5",
"name": "Deathmantle",
"faction": null,
"note": null,
"img": "_refs/picker/img/622.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=622"
},
{
"id": 668,
"cls": "rogue",
"group": "tier",
"label": "T6",
"name": "Slayer's Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/668.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=668"
},
{
"id": 801,
"cls": "rogue",
"group": "tier",
"label": "T7",
"name": "Bonescythe Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/801.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=801"
},
{
"id": -31,
"cls": "rogue",
"group": "tier",
"label": "T7",
"name": "Valorous Bonescythe Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-31.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-31"
},
{
"id": 826,
"cls": "rogue",
"group": "tier",
"label": "T8",
"name": "Terrorblade Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/826.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=826"
},
{
"id": -75,
"cls": "rogue",
"group": "tier",
"label": "T8",
"name": "Conqueror's Terrorblade Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-75.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-75"
},
{
"id": 857,
"cls": "rogue",
"group": "tier",
"label": "T9",
"name": "VanCleef's Battlegear",
"faction": "A",
"note": null,
"img": "_refs/picker/img/857.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=857"
},
{
"id": 858,
"cls": "rogue",
"group": "tier",
"label": "T9",
"name": "Garona's Battlegear",
"faction": "H",
"note": null,
"img": "_refs/picker/img/858.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=858"
},
{
"id": 890,
"cls": "rogue",
"group": "tier",
"label": "T10",
"name": "Shadowblade's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/890.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=890"
},
{
"id": -235,
"cls": "rogue",
"group": "tier",
"label": "T10",
"name": "Sanctified Shadowblade's Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-235.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-235"
},
{
"id": 577,
"cls": "rogue",
"group": "arena",
"label": "A1",
"name": "Gladiator's Vestments",
"faction": null,
"note": null,
"img": "_refs/picker/img/577.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=577"
},
{
"id": 713,
"cls": "rogue",
"group": "arena",
"label": "A2",
"name": "Merciless Gladiator's Vestments",
"faction": null,
"note": null,
"img": "_refs/picker/img/713.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=713"
},
{
"id": 730,
"cls": "rogue",
"group": "arena",
"label": "A3",
"name": "Vengeful Gladiator's Vestments",
"faction": null,
"note": null,
"img": "_refs/picker/img/730.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=730"
},
{
"id": -14,
"cls": "rogue",
"group": "arena",
"label": "A4",
"name": "Brutal Gladiator's Vestments",
"faction": null,
"note": null,
"img": "_refs/picker/img/-14.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-14"
},
{
"id": -65,
"cls": "rogue",
"group": "arena",
"label": "A5",
"name": "Deadly Gladiator's Vestments",
"faction": null,
"note": null,
"img": "_refs/picker/img/-65.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-65"
},
{
"id": -100,
"cls": "rogue",
"group": "arena",
"label": "A6",
"name": "Furious Gladiator's Vestments",
"faction": null,
"note": null,
"img": "_refs/picker/img/-100.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-100"
},
{
"id": -223,
"cls": "rogue",
"group": "arena",
"label": "A7",
"name": "Relentless Gladiator's Vestments",
"faction": null,
"note": null,
"img": "_refs/picker/img/-223.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-223"
},
{
"id": -277,
"cls": "rogue",
"group": "arena",
"label": "A8",
"name": "Wrathful Gladiator's Vestments",
"faction": null,
"note": null,
"img": "_refs/picker/img/-277.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-277"
},
{
"id": 184,
"cls": "rogue",
"group": "extra",
"label": "T0",
"name": "Shadowcraft Armor",
"faction": null,
"note": null,
"img": "_refs/picker/img/184.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=184"
},
{
"id": 497,
"cls": "rogue",
"group": "extra",
"label": "T2.5",
"name": "Deathdealer's Embrace",
"faction": null,
"note": null,
"img": "_refs/picker/img/497.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=497"
},
{
"id": 478,
"cls": "rogue",
"group": "extra",
"label": "ZG",
"name": "Madcap's Outfit",
"faction": null,
"note": null,
"img": "_refs/picker/img/478.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=478"
},
{
"id": 394,
"cls": "rogue",
"group": "extra",
"label": "PvP",
"name": "Field Marshal's Vestments",
"faction": "A",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/394.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=394"
},
{
"id": 393,
"cls": "rogue",
"group": "extra",
"label": "PvP",
"name": "Warlord's Vestments",
"faction": "H",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/393.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=393"
},
{
"id": 514,
"cls": "priest",
"group": "tier",
"label": "T0.5",
"name": "Vestments of the Virtuous",
"faction": null,
"note": null,
"img": "_refs/picker/img/514.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=514"
},
{
"id": 202,
"cls": "priest",
"group": "tier",
"label": "T1",
"name": "Vestments of Prophecy",
"faction": null,
"note": null,
"img": "_refs/picker/img/202.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=202"
},
{
"id": 211,
"cls": "priest",
"group": "tier",
"label": "T2",
"name": "Vestments of Transcendence",
"faction": null,
"note": null,
"img": "_refs/picker/img/211.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=211"
},
{
"id": 525,
"cls": "priest",
"group": "tier",
"label": "T3",
"name": "Vestments of Faith",
"faction": null,
"note": null,
"img": "_refs/picker/img/525.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=525"
},
{
"id": 663,
"cls": "priest",
"group": "tier",
"label": "T4",
"name": "Incarnate Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/663.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=663"
},
{
"id": 664,
"cls": "priest",
"group": "tier",
"label": "T4",
"name": "Incarnate Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/664.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=664"
},
{
"id": 665,
"cls": "priest",
"group": "tier",
"label": "T5",
"name": "Avatar Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/665.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=665"
},
{
"id": 666,
"cls": "priest",
"group": "tier",
"label": "T5",
"name": "Avatar Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/666.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=666"
},
{
"id": 675,
"cls": "priest",
"group": "tier",
"label": "T6",
"name": "Vestments of Absolution",
"faction": null,
"note": null,
"img": "_refs/picker/img/675.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=675"
},
{
"id": 674,
"cls": "priest",
"group": "tier",
"label": "T6",
"name": "Absolution Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/674.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=674"
},
{
"id": 804,
"cls": "priest",
"group": "tier",
"label": "T7",
"name": "Regalia of Faith",
"faction": null,
"note": null,
"img": "_refs/picker/img/804.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=804"
},
{
"id": -34,
"cls": "priest",
"group": "tier",
"label": "T7",
"name": "Valorous Regalia of Faith",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-34.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-34"
},
{
"id": 833,
"cls": "priest",
"group": "tier",
"label": "T8",
"name": "Sanctification Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/833.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=833"
},
{
"id": -82,
"cls": "priest",
"group": "tier",
"label": "T8",
"name": "Conqueror's Sanctification Regalia",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-82.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-82"
},
{
"id": 849,
"cls": "priest",
"group": "tier",
"label": "T9",
"name": "Velen's Regalia",
"faction": "A",
"note": null,
"img": "_refs/picker/img/849.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=849"
},
{
"id": 850,
"cls": "priest",
"group": "tier",
"label": "T9",
"name": "Zabra's Regalia",
"faction": "H",
"note": null,
"img": "_refs/picker/img/850.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=850"
},
{
"id": 886,
"cls": "priest",
"group": "tier",
"label": "T10",
"name": "Crimson Acolyte's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/886.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=886"
},
{
"id": -231,
"cls": "priest",
"group": "tier",
"label": "T10",
"name": "Sanctified Crimson Acolyte's Regalia",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-231.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-231"
},
{
"id": 687,
"cls": "priest",
"group": "arena",
"label": "A1",
"name": "Gladiator's Investiture",
"faction": null,
"note": null,
"img": "_refs/picker/img/687.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=687"
},
{
"id": 705,
"cls": "priest",
"group": "arena",
"label": "A2",
"name": "Merciless Gladiator's Investiture",
"faction": null,
"note": null,
"img": "_refs/picker/img/705.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=705"
},
{
"id": 728,
"cls": "priest",
"group": "arena",
"label": "A3",
"name": "Vengeful Gladiator's Investiture",
"faction": null,
"note": null,
"img": "_refs/picker/img/728.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=728"
},
{
"id": -6,
"cls": "priest",
"group": "arena",
"label": "A4",
"name": "Brutal Gladiator's Investiture",
"faction": null,
"note": null,
"img": "_refs/picker/img/-6.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-6"
},
{
"id": -57,
"cls": "priest",
"group": "arena",
"label": "A5",
"name": "Deadly Gladiator's Investiture",
"faction": null,
"note": null,
"img": "_refs/picker/img/-57.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-57"
},
{
"id": -92,
"cls": "priest",
"group": "arena",
"label": "A6",
"name": "Furious Gladiator's Investiture",
"faction": null,
"note": null,
"img": "_refs/picker/img/-92.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-92"
},
{
"id": -224,
"cls": "priest",
"group": "arena",
"label": "A7",
"name": "Relentless Gladiator's Investiture",
"faction": null,
"note": null,
"img": "_refs/picker/img/-224.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-224"
},
{
"id": -278,
"cls": "priest",
"group": "arena",
"label": "A8",
"name": "Wrathful Gladiator's Investiture",
"faction": null,
"note": null,
"img": "_refs/picker/img/-278.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-278"
},
{
"id": 182,
"cls": "priest",
"group": "extra",
"label": "T0",
"name": "Vestments of the Devout",
"faction": null,
"note": null,
"img": "_refs/picker/img/182.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=182"
},
{
"id": 507,
"cls": "priest",
"group": "extra",
"label": "T2.5",
"name": "Garments of the Oracle",
"faction": null,
"note": null,
"img": "_refs/picker/img/507.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=507"
},
{
"id": 480,
"cls": "priest",
"group": "extra",
"label": "ZG",
"name": "Confessor's Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/480.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=480"
},
{
"id": 389,
"cls": "priest",
"group": "extra",
"label": "PvP",
"name": "Field Marshal's Raiment",
"faction": "A",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/389.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=389"
},
{
"id": 390,
"cls": "priest",
"group": "extra",
"label": "PvP",
"name": "Warlord's Raiment",
"faction": "H",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/390.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=390"
},
{
"id": 792,
"cls": "dk",
"group": "tier",
"label": "T7",
"name": "Scourgeborne Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/792.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=792"
},
{
"id": -23,
"cls": "dk",
"group": "tier",
"label": "T7",
"name": "Valorous Scourgeborne Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-23.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-23"
},
{
"id": 834,
"cls": "dk",
"group": "tier",
"label": "T8",
"name": "Darkruned Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/834.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=834"
},
{
"id": -83,
"cls": "dk",
"group": "tier",
"label": "T8",
"name": "Conqueror's Darkruned Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-83.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-83"
},
{
"id": 871,
"cls": "dk",
"group": "tier",
"label": "T9",
"name": "Thassarian's Battlegear",
"faction": "A",
"note": null,
"img": "_refs/picker/img/871.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=871"
},
{
"id": 872,
"cls": "dk",
"group": "tier",
"label": "T9",
"name": "Koltira's Battlegear",
"faction": "H",
"note": null,
"img": "_refs/picker/img/872.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=872"
},
{
"id": 897,
"cls": "dk",
"group": "tier",
"label": "T10",
"name": "Scourgelord's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/897.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=897"
},
{
"id": -242,
"cls": "dk",
"group": "tier",
"label": "T10",
"name": "Sanctified Scourgelord's Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-242.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-242"
},
{
"id": -54,
"cls": "dk",
"group": "arena",
"label": "A5",
"name": "Deadly Gladiator's Desecration",
"faction": null,
"note": null,
"img": "_refs/picker/img/-54.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-54"
},
{
"id": -89,
"cls": "dk",
"group": "arena",
"label": "A6",
"name": "Furious Gladiator's Desecration",
"faction": null,
"note": null,
"img": "_refs/picker/img/-89.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-89"
},
{
"id": -215,
"cls": "dk",
"group": "arena",
"label": "A7",
"name": "Relentless Gladiator's Desecration",
"faction": null,
"note": null,
"img": "_refs/picker/img/-215.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-215"
},
{
"id": -269,
"cls": "dk",
"group": "arena",
"label": "A8",
"name": "Wrathful Gladiator's Desecration",
"faction": null,
"note": null,
"img": "_refs/picker/img/-269.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-269"
},
{
"id": 519,
"cls": "shaman",
"group": "tier",
"label": "T0.5",
"name": "The Five Thunders",
"faction": null,
"note": null,
"img": "_refs/picker/img/519.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=519"
},
{
"id": 207,
"cls": "shaman",
"group": "tier",
"label": "T1",
"name": "The Earthfury",
"faction": null,
"note": null,
"img": "_refs/picker/img/207.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=207"
},
{
"id": 216,
"cls": "shaman",
"group": "tier",
"label": "T2",
"name": "The Ten Storms",
"faction": null,
"note": null,
"img": "_refs/picker/img/216.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=216"
},
{
"id": 527,
"cls": "shaman",
"group": "tier",
"label": "T3",
"name": "The Earthshatterer",
"faction": null,
"note": null,
"img": "_refs/picker/img/527.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=527"
},
{
"id": 633,
"cls": "shaman",
"group": "tier",
"label": "T4",
"name": "Cyclone Harness",
"faction": null,
"note": null,
"img": "_refs/picker/img/633.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=633"
},
{
"id": 632,
"cls": "shaman",
"group": "tier",
"label": "T4",
"name": "Cyclone Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/632.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=632"
},
{
"id": 631,
"cls": "shaman",
"group": "tier",
"label": "T4",
"name": "Cyclone Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/631.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=631"
},
{
"id": 636,
"cls": "shaman",
"group": "tier",
"label": "T5",
"name": "Cataclysm Harness",
"faction": null,
"note": null,
"img": "_refs/picker/img/636.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=636"
},
{
"id": 635,
"cls": "shaman",
"group": "tier",
"label": "T5",
"name": "Cataclysm Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/635.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=635"
},
{
"id": 634,
"cls": "shaman",
"group": "tier",
"label": "T5",
"name": "Cataclysm Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/634.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=634"
},
{
"id": 682,
"cls": "shaman",
"group": "tier",
"label": "T6",
"name": "Skyshatter Harness",
"faction": null,
"note": null,
"img": "_refs/picker/img/682.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=682"
},
{
"id": 684,
"cls": "shaman",
"group": "tier",
"label": "T6",
"name": "Skyshatter Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/684.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=684"
},
{
"id": 683,
"cls": "shaman",
"group": "tier",
"label": "T6",
"name": "Skyshatter Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/683.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=683"
},
{
"id": 795,
"cls": "shaman",
"group": "tier",
"label": "T7",
"name": "Earthshatter Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/795.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=795"
},
{
"id": -36,
"cls": "shaman",
"group": "tier",
"label": "T7",
"name": "Valorous Earthshatter Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-36.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-36"
},
{
"id": 823,
"cls": "shaman",
"group": "tier",
"label": "T8",
"name": "Worldbreaker Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/823.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=823"
},
{
"id": -72,
"cls": "shaman",
"group": "tier",
"label": "T8",
"name": "Conqueror's Worldbreaker Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-72.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-72"
},
{
"id": 865,
"cls": "shaman",
"group": "tier",
"label": "T9",
"name": "Nobundo's Battlegear",
"faction": "A",
"note": null,
"img": "_refs/picker/img/865.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=865"
},
{
"id": 866,
"cls": "shaman",
"group": "tier",
"label": "T9",
"name": "Thrall's Battlegear",
"faction": "H",
"note": null,
"img": "_refs/picker/img/866.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=866"
},
{
"id": 894,
"cls": "shaman",
"group": "tier",
"label": "T10",
"name": "Frost Witch's Battlegear",
"faction": null,
"note": null,
"img": "_refs/picker/img/894.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=894"
},
{
"id": -239,
"cls": "shaman",
"group": "tier",
"label": "T10",
"name": "Sanctified Frost Witch's Battlegear",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-239.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-239"
},
{
"id": 578,
"cls": "shaman",
"group": "arena",
"label": "A1",
"name": "Gladiator's Earthshaker",
"faction": null,
"note": null,
"img": "_refs/picker/img/578.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=578"
},
{
"id": 703,
"cls": "shaman",
"group": "arena",
"label": "A2",
"name": "Merciless Gladiator's Earthshaker",
"faction": null,
"note": null,
"img": "_refs/picker/img/703.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=703"
},
{
"id": 732,
"cls": "shaman",
"group": "arena",
"label": "A3",
"name": "Vengeful Gladiator's Earthshaker",
"faction": null,
"note": null,
"img": "_refs/picker/img/732.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=732"
},
{
"id": -4,
"cls": "shaman",
"group": "arena",
"label": "A4",
"name": "Brutal Gladiator's Earthshaker",
"faction": null,
"note": null,
"img": "_refs/picker/img/-4.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-4"
},
{
"id": -55,
"cls": "shaman",
"group": "arena",
"label": "A5",
"name": "Deadly Gladiator's Earthshaker",
"faction": null,
"note": null,
"img": "_refs/picker/img/-55.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-55"
},
{
"id": -90,
"cls": "shaman",
"group": "arena",
"label": "A6",
"name": "Furious Gladiator's Earthshaker",
"faction": null,
"note": null,
"img": "_refs/picker/img/-90.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-90"
},
{
"id": -217,
"cls": "shaman",
"group": "arena",
"label": "A7",
"name": "Relentless Gladiator's Earthshaker",
"faction": null,
"note": null,
"img": "_refs/picker/img/-217.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-217"
},
{
"id": -271,
"cls": "shaman",
"group": "arena",
"label": "A8",
"name": "Wrathful Gladiator's Earthshaker",
"faction": null,
"note": null,
"img": "_refs/picker/img/-271.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-271"
},
{
"id": 187,
"cls": "shaman",
"group": "extra",
"label": "T0",
"name": "The Elements",
"faction": null,
"note": null,
"img": "_refs/picker/img/187.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=187"
},
{
"id": 501,
"cls": "shaman",
"group": "extra",
"label": "T2.5",
"name": "Stormcaller's Garb",
"faction": null,
"note": null,
"img": "_refs/picker/img/501.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=501"
},
{
"id": 476,
"cls": "shaman",
"group": "extra",
"label": "ZG",
"name": "Augur's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/476.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=476"
},
{
"id": 386,
"cls": "shaman",
"group": "extra",
"label": "PvP",
"name": "Warlord's Earthshaker",
"faction": "H",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/386.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=386"
},
{
"id": 517,
"cls": "mage",
"group": "tier",
"label": "T0.5",
"name": "Sorcerer's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/517.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=517"
},
{
"id": 201,
"cls": "mage",
"group": "tier",
"label": "T1",
"name": "Arcanist Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/201.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=201"
},
{
"id": 210,
"cls": "mage",
"group": "tier",
"label": "T2",
"name": "Netherwind Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/210.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=210"
},
{
"id": 526,
"cls": "mage",
"group": "tier",
"label": "T3",
"name": "Frostfire Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/526.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=526"
},
{
"id": 648,
"cls": "mage",
"group": "tier",
"label": "T4",
"name": "Aldor Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/648.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=648"
},
{
"id": 649,
"cls": "mage",
"group": "tier",
"label": "T5",
"name": "Tirisfal Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/649.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=649"
},
{
"id": 671,
"cls": "mage",
"group": "tier",
"label": "T6",
"name": "Tempest Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/671.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=671"
},
{
"id": 803,
"cls": "mage",
"group": "tier",
"label": "T7",
"name": "Frostfire Garb",
"faction": null,
"note": null,
"img": "_refs/picker/img/803.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=803"
},
{
"id": -33,
"cls": "mage",
"group": "tier",
"label": "T7",
"name": "Valorous Frostfire Garb",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-33.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-33"
},
{
"id": 836,
"cls": "mage",
"group": "tier",
"label": "T8",
"name": "Kirin Tor Garb",
"faction": null,
"note": null,
"img": "_refs/picker/img/836.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=836"
},
{
"id": -85,
"cls": "mage",
"group": "tier",
"label": "T8",
"name": "Conqueror's Kirin Tor Garb",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-85.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-85"
},
{
"id": 843,
"cls": "mage",
"group": "tier",
"label": "T9",
"name": "Khadgar's Regalia",
"faction": "A",
"note": null,
"img": "_refs/picker/img/843.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=843"
},
{
"id": 844,
"cls": "mage",
"group": "tier",
"label": "T9",
"name": "Sunstrider's Regalia",
"faction": "H",
"note": null,
"img": "_refs/picker/img/844.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=844"
},
{
"id": 883,
"cls": "mage",
"group": "tier",
"label": "T10",
"name": "Bloodmage's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/883.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=883"
},
{
"id": -228,
"cls": "mage",
"group": "tier",
"label": "T10",
"name": "Sanctified Bloodmage's Regalia",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-228.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-228"
},
{
"id": 579,
"cls": "mage",
"group": "arena",
"label": "A1",
"name": "Gladiator's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/579.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=579"
},
{
"id": 710,
"cls": "mage",
"group": "arena",
"label": "A2",
"name": "Merciless Gladiator's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/710.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=710"
},
{
"id": 724,
"cls": "mage",
"group": "arena",
"label": "A3",
"name": "Vengeful Gladiator's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/724.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=724"
},
{
"id": -11,
"cls": "mage",
"group": "arena",
"label": "A4",
"name": "Brutal Gladiator's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/-11.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-11"
},
{
"id": -62,
"cls": "mage",
"group": "arena",
"label": "A5",
"name": "Deadly Gladiator's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/-62.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-62"
},
{
"id": -97,
"cls": "mage",
"group": "arena",
"label": "A6",
"name": "Furious Gladiator's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/-97.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-97"
},
{
"id": -226,
"cls": "mage",
"group": "arena",
"label": "A7",
"name": "Relentless Gladiator's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/-226.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-226"
},
{
"id": -280,
"cls": "mage",
"group": "arena",
"label": "A8",
"name": "Wrathful Gladiator's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/-280.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-280"
},
{
"id": 181,
"cls": "mage",
"group": "extra",
"label": "T0",
"name": "Magister's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/181.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=181"
},
{
"id": 503,
"cls": "mage",
"group": "extra",
"label": "T2.5",
"name": "Enigma Vestments",
"faction": null,
"note": null,
"img": "_refs/picker/img/503.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=503"
},
{
"id": 482,
"cls": "mage",
"group": "extra",
"label": "ZG",
"name": "Illusionist's Attire",
"faction": null,
"note": null,
"img": "_refs/picker/img/482.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=482"
},
{
"id": 388,
"cls": "mage",
"group": "extra",
"label": "PvP",
"name": "Field Marshal's Regalia",
"faction": "A",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/388.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=388"
},
{
"id": 387,
"cls": "mage",
"group": "extra",
"label": "PvP",
"name": "Warlord's Regalia",
"faction": "H",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/387.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=387"
},
{
"id": 518,
"cls": "warlock",
"group": "tier",
"label": "T0.5",
"name": "Deathmist Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/518.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=518"
},
{
"id": 203,
"cls": "warlock",
"group": "tier",
"label": "T1",
"name": "Felheart Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/203.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=203"
},
{
"id": 212,
"cls": "warlock",
"group": "tier",
"label": "T2",
"name": "Nemesis Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/212.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=212"
},
{
"id": 529,
"cls": "warlock",
"group": "tier",
"label": "T3",
"name": "Plagueheart Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/529.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=529"
},
{
"id": 645,
"cls": "warlock",
"group": "tier",
"label": "T4",
"name": "Voidheart Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/645.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=645"
},
{
"id": 646,
"cls": "warlock",
"group": "tier",
"label": "T5",
"name": "Corruptor Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/646.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=646"
},
{
"id": 670,
"cls": "warlock",
"group": "tier",
"label": "T6",
"name": "Malefic Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/670.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=670"
},
{
"id": 802,
"cls": "warlock",
"group": "tier",
"label": "T7",
"name": "Plagueheart Garb",
"faction": null,
"note": null,
"img": "_refs/picker/img/802.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=802"
},
{
"id": -32,
"cls": "warlock",
"group": "tier",
"label": "T7",
"name": "Valorous Plagueheart Garb",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-32.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-32"
},
{
"id": 837,
"cls": "warlock",
"group": "tier",
"label": "T8",
"name": "Deathbringer Garb",
"faction": null,
"note": null,
"img": "_refs/picker/img/837.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=837"
},
{
"id": -86,
"cls": "warlock",
"group": "tier",
"label": "T8",
"name": "Conqueror's Deathbringer Garb",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-86.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-86"
},
{
"id": 846,
"cls": "warlock",
"group": "tier",
"label": "T9",
"name": "Kel'Thuzad's Regalia",
"faction": "A",
"note": null,
"img": "_refs/picker/img/846.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=846"
},
{
"id": 845,
"cls": "warlock",
"group": "tier",
"label": "T9",
"name": "Gul'dan's Regalia",
"faction": "H",
"note": null,
"img": "_refs/picker/img/845.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=845"
},
{
"id": 884,
"cls": "warlock",
"group": "tier",
"label": "T10",
"name": "Dark Coven's Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/884.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=884"
},
{
"id": -229,
"cls": "warlock",
"group": "tier",
"label": "T10",
"name": "Sanctified Dark Coven's Regalia",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-229.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-229"
},
{
"id": 568,
"cls": "warlock",
"group": "arena",
"label": "A1",
"name": "Gladiator's Dreadgear",
"faction": null,
"note": null,
"img": "_refs/picker/img/568.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=568"
},
{
"id": 702,
"cls": "warlock",
"group": "arena",
"label": "A2",
"name": "Merciless Gladiator's Dreadgear",
"faction": null,
"note": null,
"img": "_refs/picker/img/702.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=702"
},
{
"id": 734,
"cls": "warlock",
"group": "arena",
"label": "A3",
"name": "Vengeful Gladiator's Dreadgear",
"faction": null,
"note": null,
"img": "_refs/picker/img/734.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=734"
},
{
"id": -3,
"cls": "warlock",
"group": "arena",
"label": "A4",
"name": "Brutal Gladiator's Dreadgear",
"faction": null,
"note": null,
"img": "_refs/picker/img/-3.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-3"
},
{
"id": -56,
"cls": "warlock",
"group": "arena",
"label": "A5",
"name": "Deadly Gladiator's Felshroud",
"faction": null,
"note": null,
"img": "_refs/picker/img/-56.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-56"
},
{
"id": -91,
"cls": "warlock",
"group": "arena",
"label": "A6",
"name": "Furious Gladiator's Felshroud",
"faction": null,
"note": null,
"img": "_refs/picker/img/-91.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-91"
},
{
"id": -227,
"cls": "warlock",
"group": "arena",
"label": "A7",
"name": "Relentless Gladiator's Felshroud",
"faction": null,
"note": null,
"img": "_refs/picker/img/-227.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-227"
},
{
"id": -281,
"cls": "warlock",
"group": "arena",
"label": "A8",
"name": "Wrathful Gladiator's Felshroud",
"faction": null,
"note": null,
"img": "_refs/picker/img/-281.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-281"
},
{
"id": 183,
"cls": "warlock",
"group": "extra",
"label": "T0",
"name": "Dreadmist Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/183.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=183"
},
{
"id": 499,
"cls": "warlock",
"group": "extra",
"label": "T2.5",
"name": "Doomcaller's Attire",
"faction": null,
"note": null,
"img": "_refs/picker/img/499.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=499"
},
{
"id": 481,
"cls": "warlock",
"group": "extra",
"label": "ZG",
"name": "Demoniac's Threads",
"faction": null,
"note": null,
"img": "_refs/picker/img/481.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=481"
},
{
"id": 392,
"cls": "warlock",
"group": "extra",
"label": "PvP",
"name": "Field Marshal's Threads",
"faction": "A",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/392.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=392"
},
{
"id": 391,
"cls": "warlock",
"group": "extra",
"label": "PvP",
"name": "Warlord's Threads",
"faction": "H",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/391.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=391"
},
{
"id": 513,
"cls": "druid",
"group": "tier",
"label": "T0.5",
"name": "Feralheart Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/513.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=513"
},
{
"id": 205,
"cls": "druid",
"group": "tier",
"label": "T1",
"name": "Cenarion Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/205.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=205"
},
{
"id": 214,
"cls": "druid",
"group": "tier",
"label": "T2",
"name": "Stormrage Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/214.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=214"
},
{
"id": 521,
"cls": "druid",
"group": "tier",
"label": "T3",
"name": "Dreamwalker Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/521.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=521"
},
{
"id": 640,
"cls": "druid",
"group": "tier",
"label": "T4",
"name": "Malorne Harness",
"faction": null,
"note": null,
"img": "_refs/picker/img/640.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=640"
},
{
"id": 639,
"cls": "druid",
"group": "tier",
"label": "T4",
"name": "Malorne Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/639.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=639"
},
{
"id": 638,
"cls": "druid",
"group": "tier",
"label": "T4",
"name": "Malorne Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/638.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=638"
},
{
"id": 641,
"cls": "druid",
"group": "tier",
"label": "T5",
"name": "Nordrassil Harness",
"faction": null,
"note": null,
"img": "_refs/picker/img/641.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=641"
},
{
"id": 643,
"cls": "druid",
"group": "tier",
"label": "T5",
"name": "Nordrassil Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/643.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=643"
},
{
"id": 642,
"cls": "druid",
"group": "tier",
"label": "T5",
"name": "Nordrassil Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/642.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=642"
},
{
"id": 676,
"cls": "druid",
"group": "tier",
"label": "T6",
"name": "Thunderheart Harness",
"faction": null,
"note": null,
"img": "_refs/picker/img/676.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=676"
},
{
"id": 677,
"cls": "druid",
"group": "tier",
"label": "T6",
"name": "Thunderheart Regalia",
"faction": null,
"note": null,
"img": "_refs/picker/img/677.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=677"
},
{
"id": 678,
"cls": "druid",
"group": "tier",
"label": "T6",
"name": "Thunderheart Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/678.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=678"
},
{
"id": 800,
"cls": "druid",
"group": "tier",
"label": "T7",
"name": "Dreamwalker Garb",
"faction": null,
"note": "скріншот з варіанта Dreamwalker Battlegear",
"img": "_refs/picker/img/800.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=800"
},
{
"id": -30,
"cls": "druid",
"group": "tier",
"label": "T7",
"name": "Valorous Dreamwalker Garb",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-30.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-30"
},
{
"id": 828,
"cls": "druid",
"group": "tier",
"label": "T8",
"name": "Nightsong Garb",
"faction": null,
"note": null,
"img": "_refs/picker/img/828.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=828"
},
{
"id": -77,
"cls": "druid",
"group": "tier",
"label": "T8",
"name": "Conqueror's Nightsong Garb",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-77.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-77"
},
{
"id": 851,
"cls": "druid",
"group": "tier",
"label": "T9",
"name": "Malfurion's Garb",
"faction": "A",
"note": null,
"img": "_refs/picker/img/851.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=851"
},
{
"id": 852,
"cls": "druid",
"group": "tier",
"label": "T9",
"name": "Runetotem's Garb",
"faction": "H",
"note": null,
"img": "_refs/picker/img/852.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=852"
},
{
"id": 887,
"cls": "druid",
"group": "tier",
"label": "T10",
"name": "Lasherweave Garb",
"faction": null,
"note": null,
"img": "_refs/picker/img/887.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=887"
},
{
"id": -232,
"cls": "druid",
"group": "tier",
"label": "T10",
"name": "Sanctified Lasherweave Garb",
"faction": null,
"note": "героїчне перефарбування",
"img": "_refs/picker/img/-232.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-232"
},
{
"id": 584,
"cls": "druid",
"group": "arena",
"label": "A1",
"name": "Gladiator's Sanctuary",
"faction": null,
"note": null,
"img": "_refs/picker/img/584.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=584"
},
{
"id": 711,
"cls": "druid",
"group": "arena",
"label": "A2",
"name": "Merciless Gladiator's Sanctuary",
"faction": null,
"note": null,
"img": "_refs/picker/img/711.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=711"
},
{
"id": 721,
"cls": "druid",
"group": "arena",
"label": "A3",
"name": "Vengeful Gladiator's Sanctuary",
"faction": null,
"note": null,
"img": "_refs/picker/img/721.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=721"
},
{
"id": -12,
"cls": "druid",
"group": "arena",
"label": "A4",
"name": "Brutal Gladiator's Sanctuary",
"faction": null,
"note": null,
"img": "_refs/picker/img/-12.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-12"
},
{
"id": -63,
"cls": "druid",
"group": "arena",
"label": "A5",
"name": "Deadly Gladiator's Sanctuary",
"faction": null,
"note": null,
"img": "_refs/picker/img/-63.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-63"
},
{
"id": -98,
"cls": "druid",
"group": "arena",
"label": "A6",
"name": "Furious Gladiator's Sanctuary",
"faction": null,
"note": null,
"img": "_refs/picker/img/-98.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-98"
},
{
"id": -222,
"cls": "druid",
"group": "arena",
"label": "A7",
"name": "Relentless Gladiator's Sanctuary",
"faction": null,
"note": null,
"img": "_refs/picker/img/-222.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-222"
},
{
"id": -276,
"cls": "druid",
"group": "arena",
"label": "A8",
"name": "Wrathful Gladiator's Sanctuary",
"faction": null,
"note": null,
"img": "_refs/picker/img/-276.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=-276"
},
{
"id": 185,
"cls": "druid",
"group": "extra",
"label": "T0",
"name": "Wildheart Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/185.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=185"
},
{
"id": 493,
"cls": "druid",
"group": "extra",
"label": "T2.5",
"name": "Genesis Raiment",
"faction": null,
"note": null,
"img": "_refs/picker/img/493.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=493"
},
{
"id": 479,
"cls": "druid",
"group": "extra",
"label": "ZG",
"name": "Haruspex's Garb",
"faction": null,
"note": null,
"img": null,
"url": "https://www.wowhead.com/wotlk/item-set=479"
},
{
"id": 397,
"cls": "druid",
"group": "extra",
"label": "PvP",
"name": "Field Marshal's Sanctuary",
"faction": "A",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/397.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=397"
},
{
"id": 398,
"cls": "druid",
"group": "extra",
"label": "PvP",
"name": "Warlord's Sanctuary",
"faction": "H",
"note": "епічний PvP-сет класики",
"img": "_refs/picker/img/398.jpg",
"url": "https://www.wowhead.com/wotlk/item-set=398"
}
];
